[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer-runs = 1000
solc-version = "0.8.37"
libs = ["dependencies"]

remappings = [
    "solady@0.2.6/=dependencies/solady-0.2.6/",
]

[soldeer]
remappings_generate = false
remappings_location = "config"

[dependencies]
forge-std = "1.16.2"
solady = "0.2.6"

[fuzz]
seed = "0x544D"

[invariant]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
